hmrc/income-tax-tailor-returns-frontend

.g8/radioButtonPage/app/controllers/$className$Controller.scala, .g8/radioButtonPage/app/forms/$className$FormProvider.scala, .g8/radioButtonPage/app/models/$className$.scala, .g8/radioButtonPage/app/views/$className$AgentView.scala.html, .g8/radioButtonPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/radioButtonPage/generated-test/forms/$className$FormProviderSpec.scala, .g8/radioButtonPage/migrations/$className__snake$.sh, project/plugins.sbt
Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)
=> SASS-5796 Add agent view and options for radio button pattern

.sbtopts
Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)
=> Add sbtopts to disable supershell

.g8/checkboxPage/app/controllers/$className$Controller.scala, .g8/checkboxPage/app/forms/$className$FormProvider.scala, .g8/checkboxPage/app/models/$className$.scala, .g8/checkboxPage/app/views/$className$AgentView.scala.html, .g8/checkboxPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/checkboxPage/generated-test/forms/$className$FormProviderSpec.scala, .g8/checkboxPage/migrations/$className__snake$.sh
Edit templates to enable agent specific messages to be rendered on checkbox pages.
=> SASS-5798: Implement agent views for checkboxPage templates

conf/prod.routes
update prod.routes to match service in environments
=> update prod.routes to match service in environments

app/config/FrontendAppConfig.scala
Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)
=> feedback url change type to String from java Url

.g8/contentPage/app/controllers/$className$Controller.scala, .g8/contentPage/app/views/$className$AgentView.scala.html, .g8/contentPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/contentPage/migrations/$className__snake$.sh, app/config/FrontendAppConfig.scala, app/controllers/StartController.scala, app/views/StartAgentView.scala.html, app/views/StartView.scala.html, conf/app.routes, conf/application.conf, conf/messages.cy, conf/messages.en, test/controllers/StartControllerSpec.scala
Add landing page and update contentPage for agent views.
=> SASS-5664: Create 'Update and submit a Tax Return' page - TYR II

app/config/Module.scala, app/controllers/actions/IdentifierAction.scala, conf/application.conf, test/controllers/actions/AuthActionSpec.scala
=> [SASS-5899] Early private launch setup

app/config/FrontendAppConfig.scala, app/controllers/actions/IdentifierAction.scala, conf/app.routes, conf/application.conf, test/controllers/actions/AuthActionSpec.scala
=> SASS-5899 Update GGW sign in url and enforce relative and absolute URL policy

conf/application.conf, conf/prod.routes, test/controllers/actions/AuthActionSpec.scala
=> SASS-5937 Update tailoring root url

.g8/checkboxPage/app/controllers/$className$Controller.scala, .g8/contentPage/app/controllers/$className$Controller.scala, .g8/datePage/app/controllers/$className$Controller.scala, .g8/intPage/app/controllers/$className$Controller.scala, .g8/multipleQuestionsPage/app/controllers/$className$Controller.scala, .g8/radioButtonPage/app/controllers/$className$Controller.scala, .g8/radioButtonPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/stringPage/app/controllers/$className$Controller.scala, .g8/yesNoPage/app/controllers/$className$Controller.scala, app/controllers/AddSectionsController.scala, app/controllers/CharitableDonationsController.scala, app/controllers/ChildBenefitController.scala, app/controllers/ChildBenefitIncomeController.scala, app/controllers/FosterCarerController.scala, app/controllers/HighIncomeChildBenefitChargeController.scala, app/controllers/IndexController.scala, app/controllers/JourneyRecoveryController.scala, app/controllers/KeepAliveController.scala, app/controllers/MarriageAllowanceController.scala, app/controllers/PatentRoyaltyPaymentsController.scala, app/controllers/StartController.scala, app/controllers/TaxAvoidanceSchemesController.scala, app/controllers/TaxReturnNotReadyController.scala, app/controllers/aboutyou/UkResidenceStatusController.scala, app/controllers/aboutyou/YourResidenceStatusController.scala, app/controllers/actions/TaxYearAction.scala, test/controllers/actions/TaxYearActionSpec.scala
=> add taxYearAction and update Controllers and templates

app/views/TaxReturnNotReadyAgentView.scala.html, app/views/TaxReturnNotReadyView.scala.html, conf/messages.cy, conf/messages.en
create "Your Tax Return is not ready to fill in yet" page
=> Your Tax Return is not ready to fill in yet page - TYR II

conf/messages.cy, conf/messages.en
=> SASS-6008 Update service name

app/views/aboutyou/MarriageAllowanceAgentView.scala.html
=> SASS-6011 Fix title for marriage allowance page agent view

conf/messages.en
A word was found to be missing in agent version of the page during QA testing, this commit adds the missing content.
=> SASS-6027: add missing word to messages for TaxAvoidanceSchemes page

app/navigation/JourneyNavigator.scala, app/navigation/PrivateBetaNavigator.scala, test/navigation/JourneyNavigatorSpec.scala, test/navigation/PrivateBetaNavigatorSpec.scala
Navigation of Payments into pensions
=> SASS-6356: Navigation of Payments into pensions

app/services/AddSectionsService.scala, app/services/JourneyAddSectionsService.scala, app/services/PrivateBetaAddSectionsService.scala, test/controllers/AddSectionsControllerSpec.scala, test/services/JourneyAddSectionsServiceSpec.scala, test/services/PrivateBetaAddSectionsServiceSpec.scala
=> remaining logic for add sections page

app/views/templates/Layout.scala.html, app/views/templates/UnauthenticatedLayout.scala.html
Update service link in header.
=> Change service url redirect

project/AppDependencies.scala, project/plugins.sbt
Update play-frontend-hmrc version for new crown.
=> SASS-7338: Update dependencies

app/audit/AuditDetail.scala, app/audit/AuditModel.scala, app/audit/AuditService.scala, app/controllers/AddSectionsController.scala, app/viewmodels/AddSectionsViewModel.scala, app/views/AddSectionsAgentView.scala.html, app/views/AddSectionsView.scala.html, conf/app.routes, test/audit/AuditServiceSpec.scala, test/controllers/AddSectionsControllerSpec.scala
Add explicit audit events Completed/Incomplete
=> SASS-7373: Add explicit audit events Completed/Incomplete

README.md, project/plugins.sbt
=> SASS-7740: Update README with service manager config changes

app/config/FrontendAppConfig.scala, app/controllers/AddSectionsController.scala, conf/application.conf, test/base/SpecBase.scala, test/controllers/AddSectionsControllerSpec.scala
=> SASS-8194 Redirect to submission frontend tasklist

app/models/TagStatus.scala, app/viewmodels/AddSectionsViewModel.scala, app/views/AddSectionsAgentView.scala.html, app/views/AddSectionsView.scala.html, conf/messages.cy, test/controllers/AddSectionsControllerSpec.scala
=> SASS-8190: Update the Tailoring task list to use the new twirl tasklist component as per GDS standards

app/connectors/TaskListDataConnector.scala, app/controllers/AddSectionsController.scala, app/models/tasklist/SectionTitle.scala, app/models/tasklist/StatusTag.scala, app/models/tasklist/TaskListData.scala, app/models/tasklist/TaskListModel.scala, app/models/tasklist/TaskListSection.scala, app/models/tasklist/TaskListSectionItem.scala, app/models/tasklist/TaskStatus.scala, app/models/tasklist/TaskTitle.scala, app/services/TaskListDataService.scala, app/services/TaskListService.scala, it/test/connectors/TaskListDataConnectorSpec.scala, test/base/SpecBase.scala, test/controllers/AddSectionsControllerSpec.scala, test/models/tasklist/TaskListDataSpec.scala, test/services/TaskListDataServiceSpec.scala
Derive task list model from tailoring responses.
=> Sass 8195 - Save data for task list

app/config/FrontendAppConfig.scala, app/controllers/actions/IdentifierAction.scala, conf/application.conf, conf/logback.xml, project/build.properties, project/plugins.sbt, test/controllers/actions/AuthActionSpec.scala
=> SASS-8414: Update the Sign-Up link in Tailoring

app/models/pensions/PaymentsIntoPensions.scala, app/services/TaskListDataService.scala, conf/logback.xml, conf/messages.cy, conf/messages.en, project/build.properties, project/plugins.sbt
=> SASS-8366: Add an additional Option to the Payment Into Pensions Page

app/config/FrontendAppConfig.scala, app/services/TaskListDataService.scala, conf/application.conf, test/services/TaskListDataServiceSpec.scala
=> SASS-8425 Added linear journey to common task list items

app/services/TaskListDataService.scala
Annual allowances should have been one higher in the order of tasks.
=> SASS-8603: Update order of task items

app/audit/AuditModel.scala, app/controllers/AddSectionsController.scala, test/audit/AuditServiceSpec.scala
=> SASS-8680: fix audit events

app/services/TaskListDataService.scala
=> SASS-8672 Added UK residence status to tasklist data for no options

app/controllers/testonly/TestOnlyAddData.scala, app/utils/TailoringDataHelper.scala, conf/testOnlyDoNotUseInAppConf.routes, test/controllers/testonly/TestOnlyAddDataSpec.scala
=> SASS-8671 added testOnly endpoint to add tailoring data

app/config/FrontendAppConfig.scala, app/services/TaskListDataService.scala
Update charitable donations links, fix jsa/esa issue
=> SASS-9530: Update charitable donations links, fix jsa/esa issue

app/services/TaskListDataService.scala
=> SASS-9593: Amended urls to be used for Interest section of the Task List

app/config/FrontendAppConfig.scala, app/services/TaskListDataService.scala
Update for dividends mini journeys
=> SASS-9627: Update for dividends mini journeys

app/config/FrontendAppConfig.scala, app/services/TaskListDataService.scala
=> SASS-9691: Add param to url for gains

app/config/FrontendAppConfig.scala, app/services/TaskListDataService.scala
=> SASS-10003: Amended urls to be used for Employment section of the Task List

app/config/FrontendAppConfig.scala, app/models/SectionState.scala, app/services/TaskListDataService.scala
=> SASS-10055: Update CIS url

app/services/AddSectionsService.scala, test/services/JourneyAddSectionsServiceSpec.scala, test/services/PrivateBetaAddSectionsServiceSpec.scala
Linked to main ticket - SASS-7762
Updated functionality for NotStarted Status based on how UK Residence Status question is answered.
=> SASS-7762: Task List-UK Residence Status hyperlink

app/services/TaskListDataService.scala, test/services/TaskListDataServiceSpec.scala
Add a check for the CIS value to be true before showing the Self Employment section. (this logic will need expanding when self-employment is integrated with the common task list)
=> SASS-10085: Update logic for showing CIS task

app/config/FrontendAppConfig.scala, app/config/Module.scala, app/controllers/actions/IdentifierAction.scala, app/models/Enrolment.scala, app/models/requests/IdentifierRequest.scala, build.sbt, check.sh, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/controllers/actions/AuthActionSpec.scala, test/services/JourneyAddSectionsServiceSpec.scala, test/services/PrivateBetaAddSectionsServiceSpec.scala
- Added secondary agent logic
- Added tests
- Added feature flag
=> SASS-10665 Enabling Multi-Agent for income-tax-tailor-returns-frontend

app/controllers/workandbenefits/ConstructionIndustrySchemeController.scala, app/views/workandbenefits/ConstructionIndustrySchemeAgentView.scala.html, app/views/workandbenefits/ConstructionIndustrySchemeView.scala.html, conf/messages.cy, conf/messages.en, test/controllers/workandbenefits/ConstructionIndustrySchemeControllerSpec.scala
- Dependency update
- View changes
- Feature flagged changes
- New tests added
=> SASS-11068: Construction Industry Scheme (CIS) page- Pre-pop

app/controllers/propertypensionsinvestments/RentalIncomeController.scala, app/views/propertypensionsinvestments/RentalIncomeAgentView.scala.html, app/views/propertypensionsinvestments/RentalIncomeView.scala.html, conf/messages.cy, conf/messages.en, test/controllers/propertypensionsinvestments/RentalIncomeControllerSpec.scala, test/controllers/workandbenefits/JobseekersAllowanceControllerSpec.scala
- UI Changes
- Tests updated
- Welsh request added to relevant ticket
=> SASS-11102: Property - PrePop

conf/messages.cy
Changes for historical, CIS and Property
=> SASS-11159: Welsh changes for historical, CIS and Property

app/config/FrontendAppConfig.scala, app/controllers/SupportingAgentAuthErrorController.scala, app/controllers/actions/IdentifierAction.scala, app/models/requests/IdentifierRequest.scala, app/views/SupportingAgentAuthErrorView.scala.html, conf/app.routes, conf/application.conf, conf/messages.cy, conf/messages.en, project/AppDependencies.scala, test/base/SpecBase.scala, test/controllers/SupportingAgentAuthErrorControllerSpec.scala, test/controllers/actions/AuthActionSpec.scala
=> SASS-11227: Enabling Multi- Agent for Income-tax-tailor-return - Frontend

app/config/FrontendAppConfig.scala, app/connectors/CisConnector.scala, app/connectors/PropertyConnector.scala, app/controllers/ControllerWithPrePop.scala, app/controllers/propertypensionsinvestments/RentalIncomeController.scala, app/controllers/workandbenefits/ConstructionIndustrySchemeController.scala, app/forms/propertypensionsinvestments/RentalIncomeFormProvider.scala, app/models/prePopulation/CisPrePopulationResponse.scala, app/models/prePopulation/PropertyPrePopulationResponse.scala, app/services/PrePopulationService.scala, conf/application.conf, it/test/connectors/CisConnectorSpec.scala, it/test/connectors/PropertyConnectorSpec.scala, test/connectors/CisConnectorSpec.scala, test/connectors/IncomeTaxCisConnectorSpec.scala, test/connectors/PropertyConnectorSpec.scala, test/controllers/ControllerWithPrePopSpecBase.scala, test/controllers/propertypensionsinvestments/RentalIncomeControllerSpec.scala, test/controllers/workandbenefits/ConstructionIndustrySchemeControllerSpec.scala, test/mocks/MockAppConfig.scala, test/mocks/MockCisConnector.scala, test/mocks/MockPropertyConnector.scala, test/models/prePopulation/CisPrePopulationResponseSpec.scala, test/models/prePopulation/IncomeTaxCisPrePopulationResponseSpec.scala, test/models/prePopulation/PropertyPrePopulationResponseSpec.scala, test/services/PrePopulationServiceSpec.scala
- Few CIS test issues fixed
- Added property url's
- Added property tests
- Updated Proeprrty controller
- Renamed IncomeTaxCis -> Cis to fit the naming convention for the rest of the files
=> SASS-11298: Perform end to end testing for the Property backend

app/config/Module.scala
=> SASS-11298: Reverted session data .eagerly

app/config/FrontendAppConfig.scala, conf/application.conf
App-Config-Base:
- https://github.com/hmrc/app-config-base/pull/12028
=> [SASS-11619] Improve host entry name for v&c µService

app/config/FrontendAppConfig.scala, app/models/tasklist/SectionTitle.scala, app/models/tasklist/TaskTitle.scala, app/services/TaskListDataService.scala, conf/application.conf, test/models/tasklist/SectionTitleSpec.scala, test/models/tasklist/TaskTitleSpec.scala, test/services/TaskListDataServiceSpec.scala
**Note:**
- #137 
- ☝️ this needs to be reviewed and merged first. Then I will rebase this PR from `main`. To view the specific changes for this PR, see this [commit](https://github.com/hmrc/income-tax-tailor-returns-frontend/pull/138/commits/ddaff93ff7646747feeffeaffb3063cfff12ec19)
App-Config-Base PR:
- https://github.com/hmrc/app-config-base/pull/12011
=> [SASS-11598] Add UkProperty, ForeignProperty and UkForeignProperty to saved tailoring task list
